In [9]:
import numpy as np

In [10]:
#Write a NumPy program to create an array of all even integers from 30 to 70.
even_array = np.arange(30, 71, 2)
print(even_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [15]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal.
random_array = np.random.randn(15)
print(random_array)

[ 1.53514971 -0.2225553  -0.50003312 -1.16786959 -0.14816642 -2.05664594
 -0.20570813  0.68437289 -0.67617018  0.14066492 -0.83589201 -0.53779894
 -0.71974373  0.68327199 -0.19189957]


In [16]:
#How to compute the cross-product of two matrices in NumPy?
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))

cross_product = np.cross(matrix1, matrix2)
print(cross_product)

[[-8.21303952e-03 -4.40601530e-02  5.24534199e-02]
 [-2.01199642e-01  3.52476557e-01  6.63682203e-02]
 [ 5.26990431e-01 -5.73165847e-05 -3.14956018e-01]]


In [17]:
#How to compute the determinant of an array using NumPy?
matrix = np.random.random((3, 3))
determinant = np.linalg.det(matrix)
print(determinant)

0.09941154887198732


In [18]:
#How to create a 3x3x3 array with random values using NumPy?
random_3d_array = np.random.random((3, 3, 3))
print(random_3d_array)

[[[0.68305162 0.88271418 0.21224842]
  [0.97412948 0.23239772 0.2708445 ]
  [0.28639204 0.84871439 0.31071124]]

 [[0.25897889 0.79019395 0.67479238]
  [0.1337057  0.08412318 0.25671697]
  [0.33270466 0.51443535 0.43008876]]

 [[0.6197269  0.17584986 0.76435714]
  [0.01795421 0.61384262 0.61974185]
  [0.5484537  0.86379388 0.91948817]]]


In [19]:
#How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?
random_5x5_array = np.random.random((5, 5))
min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.038227132971085376
Maximum value: 0.9728023427162824


In [20]:
#How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?
given_array = np.random.random((3, 4))

mean = np.mean(given_array, axis=1)
std_dev = np.std(given_array, axis=1)
variance = np.var(given_array, axis=1)

print("Mean along the second axis:", mean)
print("Standard Deviation along the second axis:", std_dev)
print("Variance along the second axis:", variance)


Mean along the second axis: [0.56451141 0.45457431 0.58808346]
Standard Deviation along the second axis: [0.3145781  0.22144204 0.29554168]
Variance along the second axis: [0.09895938 0.04903658 0.08734488]
